CREATE TABLE `algorithms` (
  `id` INT(11) AUTO_INCREMENT,
  `name`    VARCHAR(64)  NOT NULL COMMENT '算法的名称',
  `desc`    VARCHAR(256)  NOT NULL COMMENT '算法的描述',
  `created_at`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(`id`)
) ENGINE = INNODB CHARSET = UTF8 COMMENT = '保存每个算法的名称';
